#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="${ROOT_DIR}/dist"
VERSION="$(tr -d '[:space:]' < "${ROOT_DIR}/VERSION")"
RELEASE_TAG="${RUNTIME_RELEASE_TAG:-v${VERSION}}"

NODE_RUNTIME_VERSION="${NODE_RUNTIME_VERSION:-v20.20.0}"
NODE_RUNTIME_URL="${NODE_RUNTIME_URL:-https://nodejs.org/dist/${NODE_RUNTIME_VERSION}/node-${NODE_RUNTIME_VERSION}-linux-x64.tar.xz}"
NODE_RUNTIME_ASSET_NAME="${NODE_RUNTIME_ASSET_NAME:-node-runtime-${NODE_RUNTIME_VERSION#v}-linux-x86_64.tar.xz}"

PYTHON_STANDALONE_TAG="${PYTHON_STANDALONE_TAG:-20260211}"
PYTHON_RUNTIME_VERSION="${PYTHON_RUNTIME_VERSION:-3.12.12}"
PYTHON_RUNTIME_URL="${PYTHON_RUNTIME_URL:-https://github.com/astral-sh/python-build-standalone/releases/download/${PYTHON_STANDALONE_TAG}/cpython-${PYTHON_RUNTIME_VERSION}+${PYTHON_STANDALONE_TAG}-x86_64-unknown-linux-gnu-install_only.tar.gz}"
PYTHON_RUNTIME_ASSET_NAME="${PYTHON_RUNTIME_ASSET_NAME:-python-runtime-cpython-${PYTHON_RUNTIME_VERSION}+${PYTHON_STANDALONE_TAG}-linux-x86_64.tar.gz}"

MANIFEST_OUTPUT_NAME="runtime-manifest-linux-x86_64.txt"
MANIFEST_OUTPUT_PATH="${DIST_DIR}/${MANIFEST_OUTPUT_NAME}"
SOURCE_MANIFEST_PATH="${ROOT_DIR}/manifests/${MANIFEST_OUTPUT_NAME}"
WRITE_SOURCE_MANIFEST="${WRITE_SOURCE_MANIFEST:-0}"
CHECKSUM_SIGNATURE_ASSET_NAME="${CHECKSUM_SIGNATURE_ASSET_NAME:-SHA256SUMS.sig}"

resolve_repo_slug() {
  if [ -n "${RUNTIME_REPO_SLUG:-}" ]; then
    printf '%s\n' "${RUNTIME_REPO_SLUG}"
    return
  fi

  local remote_url
  remote_url="$(git -C "${ROOT_DIR}" remote get-url github 2>/dev/null || git -C "${ROOT_DIR}" remote get-url origin 2>/dev/null || true)"
  if [ -z "${remote_url}" ]; then
    echo "Cannot resolve git remote URL for release slug." >&2
    return 1
  fi

  if printf '%s' "${remote_url}" | grep -q '^https://github.com/'; then
    printf '%s\n' "${remote_url}" | sed -E 's#https://github.com/##; s#\.git$##'
    return
  fi

  if printf '%s' "${remote_url}" | grep -q '^git@github.com:'; then
    printf '%s\n' "${remote_url}" | sed -E 's#git@github.com:##; s#\.git$##'
    return
  fi

  echo "Unsupported remote URL format: ${remote_url}" >&2
  return 1
}

download_file() {
  local url="$1"
  local out="$2"
  local tmp="${out}.part"

  if command -v curl >/dev/null 2>&1; then
    curl -fsSL --retry 3 --retry-delay 2 --connect-timeout 20 -o "${tmp}" "${url}"
  elif command -v wget >/dev/null 2>&1; then
    wget --tries=3 --timeout=20 -O "${tmp}" "${url}"
  else
    echo "Neither curl nor wget is available." >&2
    return 1
  fi
  mv "${tmp}" "${out}"
}

sha256_of() {
  sha256sum "$1" | awk '{print $1}'
}

mkdir -p "${DIST_DIR}" "${ROOT_DIR}/manifests"

NODE_RUNTIME_PATH="${DIST_DIR}/${NODE_RUNTIME_ASSET_NAME}"
PYTHON_RUNTIME_PATH="${DIST_DIR}/${PYTHON_RUNTIME_ASSET_NAME}"

echo "Downloading node runtime: ${NODE_RUNTIME_URL}"
download_file "${NODE_RUNTIME_URL}" "${NODE_RUNTIME_PATH}"

echo "Downloading python runtime: ${PYTHON_RUNTIME_URL}"
download_file "${PYTHON_RUNTIME_URL}" "${PYTHON_RUNTIME_PATH}"

NODE_SHA256="$(sha256_of "${NODE_RUNTIME_PATH}")"
PYTHON_SHA256="$(sha256_of "${PYTHON_RUNTIME_PATH}")"
REPO_SLUG="$(resolve_repo_slug)"
RELEASE_BASE_URL="https://github.com/${REPO_SLUG}/releases/download/${RELEASE_TAG}"
CHECKSUM_SIGNATURE_URL="${RELEASE_BASE_URL}/${CHECKSUM_SIGNATURE_ASSET_NAME}"

cat > "${MANIFEST_OUTPUT_PATH}" <<EOF
# Generated by scripts/build-runtime-assets.sh
manifest_version|1
artifact|node|${NODE_RUNTIME_VERSION#v}|linux-x86_64|${RELEASE_BASE_URL}/${NODE_RUNTIME_ASSET_NAME}|-|${NODE_SHA256}|${CHECKSUM_SIGNATURE_URL}
artifact|python|${PYTHON_RUNTIME_VERSION}|linux-x86_64|${RELEASE_BASE_URL}/${PYTHON_RUNTIME_ASSET_NAME}|-|${PYTHON_SHA256}|${CHECKSUM_SIGNATURE_URL}
EOF

if [ "${WRITE_SOURCE_MANIFEST}" = "1" ]; then
  cp "${MANIFEST_OUTPUT_PATH}" "${SOURCE_MANIFEST_PATH}"
fi

echo "Runtime assets generated:"
ls -lh "${NODE_RUNTIME_PATH}" "${PYTHON_RUNTIME_PATH}" "${MANIFEST_OUTPUT_PATH}"
echo "Node sha256:   ${NODE_SHA256}"
echo "Python sha256: ${PYTHON_SHA256}"
